# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more. To authenticate use the string 'Bearer ' followed by the token which can be obtained at https://www.oanda.com/demo-account/tpa/personal_token  # noqa: E501

    OpenAPI spec version: 3.0.23
    Contact: api@oanda.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oanda.models.position_book import PositionBook  # noqa: F401,E501


class InlineResponse20031(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position_book': 'PositionBook'
    }

    attribute_map = {
        'position_book': 'positionBook'
    }

    def __init__(self, position_book=None):  # noqa: E501
        """InlineResponse20031 - a model defined in Swagger"""  # noqa: E501

        self._position_book = None
        self.discriminator = None

        if position_book is not None:
            self.position_book = position_book

    @property
    def position_book(self):
        """Gets the position_book of this InlineResponse20031.  # noqa: E501


        :return: The position_book of this InlineResponse20031.  # noqa: E501
        :rtype: PositionBook
        """
        return self._position_book

    @position_book.setter
    def position_book(self, position_book):
        """Sets the position_book of this InlineResponse20031.


        :param position_book: The position_book of this InlineResponse20031.  # noqa: E501
        :type: PositionBook
        """

        self._position_book = position_book

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20031):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
