# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more. To authenticate use the string 'Bearer ' followed by the token which can be obtained at https://www.oanda.com/demo-account/tpa/personal_token  # noqa: E501

    OpenAPI spec version: 3.0.23
    Contact: api@oanda.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oanda.models.transaction import Transaction  # noqa: F401,E501


class InlineResponse4002(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_reject_transaction': 'Transaction',
        'related_transaction_i_ds': 'list[str]',
        'last_transaction_id': 'str',
        'error_code': 'str',
        'error_message': 'str'
    }

    attribute_map = {
        'order_reject_transaction': 'orderRejectTransaction',
        'related_transaction_i_ds': 'relatedTransactionIDs',
        'last_transaction_id': 'lastTransactionID',
        'error_code': 'errorCode',
        'error_message': 'errorMessage'
    }

    def __init__(self, order_reject_transaction=None, related_transaction_i_ds=None, last_transaction_id=None, error_code=None, error_message=None):  # noqa: E501
        """InlineResponse4002 - a model defined in Swagger"""  # noqa: E501

        self._order_reject_transaction = None
        self._related_transaction_i_ds = None
        self._last_transaction_id = None
        self._error_code = None
        self._error_message = None
        self.discriminator = None

        if order_reject_transaction is not None:
            self.order_reject_transaction = order_reject_transaction
        if related_transaction_i_ds is not None:
            self.related_transaction_i_ds = related_transaction_i_ds
        if last_transaction_id is not None:
            self.last_transaction_id = last_transaction_id
        if error_code is not None:
            self.error_code = error_code
        if error_message is not None:
            self.error_message = error_message

    @property
    def order_reject_transaction(self):
        """Gets the order_reject_transaction of this InlineResponse4002.  # noqa: E501


        :return: The order_reject_transaction of this InlineResponse4002.  # noqa: E501
        :rtype: Transaction
        """
        return self._order_reject_transaction

    @order_reject_transaction.setter
    def order_reject_transaction(self, order_reject_transaction):
        """Sets the order_reject_transaction of this InlineResponse4002.


        :param order_reject_transaction: The order_reject_transaction of this InlineResponse4002.  # noqa: E501
        :type: Transaction
        """

        self._order_reject_transaction = order_reject_transaction

    @property
    def related_transaction_i_ds(self):
        """Gets the related_transaction_i_ds of this InlineResponse4002.  # noqa: E501

        The IDs of all Transactions that were created while satisfying the request.  # noqa: E501

        :return: The related_transaction_i_ds of this InlineResponse4002.  # noqa: E501
        :rtype: list[str]
        """
        return self._related_transaction_i_ds

    @related_transaction_i_ds.setter
    def related_transaction_i_ds(self, related_transaction_i_ds):
        """Sets the related_transaction_i_ds of this InlineResponse4002.

        The IDs of all Transactions that were created while satisfying the request.  # noqa: E501

        :param related_transaction_i_ds: The related_transaction_i_ds of this InlineResponse4002.  # noqa: E501
        :type: list[str]
        """

        self._related_transaction_i_ds = related_transaction_i_ds

    @property
    def last_transaction_id(self):
        """Gets the last_transaction_id of this InlineResponse4002.  # noqa: E501

        The ID of the most recent Transaction created for the Account.  # noqa: E501

        :return: The last_transaction_id of this InlineResponse4002.  # noqa: E501
        :rtype: str
        """
        return self._last_transaction_id

    @last_transaction_id.setter
    def last_transaction_id(self, last_transaction_id):
        """Sets the last_transaction_id of this InlineResponse4002.

        The ID of the most recent Transaction created for the Account.  # noqa: E501

        :param last_transaction_id: The last_transaction_id of this InlineResponse4002.  # noqa: E501
        :type: str
        """

        self._last_transaction_id = last_transaction_id

    @property
    def error_code(self):
        """Gets the error_code of this InlineResponse4002.  # noqa: E501

        The code of the error that has occurred. This field may not be returned for some errors.  # noqa: E501

        :return: The error_code of this InlineResponse4002.  # noqa: E501
        :rtype: str
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this InlineResponse4002.

        The code of the error that has occurred. This field may not be returned for some errors.  # noqa: E501

        :param error_code: The error_code of this InlineResponse4002.  # noqa: E501
        :type: str
        """

        self._error_code = error_code

    @property
    def error_message(self):
        """Gets the error_message of this InlineResponse4002.  # noqa: E501

        The human-readable description of the error that has occurred.  # noqa: E501

        :return: The error_message of this InlineResponse4002.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this InlineResponse4002.

        The human-readable description of the error that has occurred.  # noqa: E501

        :param error_message: The error_message of this InlineResponse4002.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
