# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more. To authenticate use the string 'Bearer ' followed by the token which can be obtained at https://www.oanda.com/demo-account/tpa/personal_token  # noqa: E501

    OpenAPI spec version: 3.0.23
    Contact: api@oanda.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from oanda.models.order_cancel_transaction import OrderCancelTransaction  # noqa: F401,E501
from oanda.models.order_fill_transaction import OrderFillTransaction  # noqa: F401,E501
from oanda.models.stop_loss_order_transaction import StopLossOrderTransaction  # noqa: F401,E501
from oanda.models.take_profit_order_transaction import TakeProfitOrderTransaction  # noqa: F401,E501
from oanda.models.trailing_stop_loss_order_transaction import TrailingStopLossOrderTransaction  # noqa: F401,E501


class InlineResponse20028(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'take_profit_order_cancel_transaction': 'OrderCancelTransaction',
        'take_profit_order_transaction': 'TakeProfitOrderTransaction',
        'take_profit_order_fill_transaction': 'OrderFillTransaction',
        'take_profit_order_created_cancel_transaction': 'OrderCancelTransaction',
        'stop_loss_order_cancel_transaction': 'OrderCancelTransaction',
        'stop_loss_order_transaction': 'StopLossOrderTransaction',
        'stop_loss_order_fill_transaction': 'OrderFillTransaction',
        'stop_loss_order_created_cancel_transaction': 'OrderCancelTransaction',
        'trailing_stop_loss_order_cancel_transaction': 'OrderCancelTransaction',
        'trailing_stop_loss_order_transaction': 'TrailingStopLossOrderTransaction',
        'related_transaction_i_ds': 'list[str]',
        'last_transaction_id': 'str'
    }

    attribute_map = {
        'take_profit_order_cancel_transaction': 'takeProfitOrderCancelTransaction',
        'take_profit_order_transaction': 'takeProfitOrderTransaction',
        'take_profit_order_fill_transaction': 'takeProfitOrderFillTransaction',
        'take_profit_order_created_cancel_transaction': 'takeProfitOrderCreatedCancelTransaction',
        'stop_loss_order_cancel_transaction': 'stopLossOrderCancelTransaction',
        'stop_loss_order_transaction': 'stopLossOrderTransaction',
        'stop_loss_order_fill_transaction': 'stopLossOrderFillTransaction',
        'stop_loss_order_created_cancel_transaction': 'stopLossOrderCreatedCancelTransaction',
        'trailing_stop_loss_order_cancel_transaction': 'trailingStopLossOrderCancelTransaction',
        'trailing_stop_loss_order_transaction': 'trailingStopLossOrderTransaction',
        'related_transaction_i_ds': 'relatedTransactionIDs',
        'last_transaction_id': 'lastTransactionID'
    }

    def __init__(self, take_profit_order_cancel_transaction=None, take_profit_order_transaction=None, take_profit_order_fill_transaction=None, take_profit_order_created_cancel_transaction=None, stop_loss_order_cancel_transaction=None, stop_loss_order_transaction=None, stop_loss_order_fill_transaction=None, stop_loss_order_created_cancel_transaction=None, trailing_stop_loss_order_cancel_transaction=None, trailing_stop_loss_order_transaction=None, related_transaction_i_ds=None, last_transaction_id=None):  # noqa: E501
        """InlineResponse20028 - a model defined in Swagger"""  # noqa: E501

        self._take_profit_order_cancel_transaction = None
        self._take_profit_order_transaction = None
        self._take_profit_order_fill_transaction = None
        self._take_profit_order_created_cancel_transaction = None
        self._stop_loss_order_cancel_transaction = None
        self._stop_loss_order_transaction = None
        self._stop_loss_order_fill_transaction = None
        self._stop_loss_order_created_cancel_transaction = None
        self._trailing_stop_loss_order_cancel_transaction = None
        self._trailing_stop_loss_order_transaction = None
        self._related_transaction_i_ds = None
        self._last_transaction_id = None
        self.discriminator = None

        if take_profit_order_cancel_transaction is not None:
            self.take_profit_order_cancel_transaction = take_profit_order_cancel_transaction
        if take_profit_order_transaction is not None:
            self.take_profit_order_transaction = take_profit_order_transaction
        if take_profit_order_fill_transaction is not None:
            self.take_profit_order_fill_transaction = take_profit_order_fill_transaction
        if take_profit_order_created_cancel_transaction is not None:
            self.take_profit_order_created_cancel_transaction = take_profit_order_created_cancel_transaction
        if stop_loss_order_cancel_transaction is not None:
            self.stop_loss_order_cancel_transaction = stop_loss_order_cancel_transaction
        if stop_loss_order_transaction is not None:
            self.stop_loss_order_transaction = stop_loss_order_transaction
        if stop_loss_order_fill_transaction is not None:
            self.stop_loss_order_fill_transaction = stop_loss_order_fill_transaction
        if stop_loss_order_created_cancel_transaction is not None:
            self.stop_loss_order_created_cancel_transaction = stop_loss_order_created_cancel_transaction
        if trailing_stop_loss_order_cancel_transaction is not None:
            self.trailing_stop_loss_order_cancel_transaction = trailing_stop_loss_order_cancel_transaction
        if trailing_stop_loss_order_transaction is not None:
            self.trailing_stop_loss_order_transaction = trailing_stop_loss_order_transaction
        if related_transaction_i_ds is not None:
            self.related_transaction_i_ds = related_transaction_i_ds
        if last_transaction_id is not None:
            self.last_transaction_id = last_transaction_id

    @property
    def take_profit_order_cancel_transaction(self):
        """Gets the take_profit_order_cancel_transaction of this InlineResponse20028.  # noqa: E501


        :return: The take_profit_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderCancelTransaction
        """
        return self._take_profit_order_cancel_transaction

    @take_profit_order_cancel_transaction.setter
    def take_profit_order_cancel_transaction(self, take_profit_order_cancel_transaction):
        """Sets the take_profit_order_cancel_transaction of this InlineResponse20028.


        :param take_profit_order_cancel_transaction: The take_profit_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderCancelTransaction
        """

        self._take_profit_order_cancel_transaction = take_profit_order_cancel_transaction

    @property
    def take_profit_order_transaction(self):
        """Gets the take_profit_order_transaction of this InlineResponse20028.  # noqa: E501


        :return: The take_profit_order_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: TakeProfitOrderTransaction
        """
        return self._take_profit_order_transaction

    @take_profit_order_transaction.setter
    def take_profit_order_transaction(self, take_profit_order_transaction):
        """Sets the take_profit_order_transaction of this InlineResponse20028.


        :param take_profit_order_transaction: The take_profit_order_transaction of this InlineResponse20028.  # noqa: E501
        :type: TakeProfitOrderTransaction
        """

        self._take_profit_order_transaction = take_profit_order_transaction

    @property
    def take_profit_order_fill_transaction(self):
        """Gets the take_profit_order_fill_transaction of this InlineResponse20028.  # noqa: E501


        :return: The take_profit_order_fill_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderFillTransaction
        """
        return self._take_profit_order_fill_transaction

    @take_profit_order_fill_transaction.setter
    def take_profit_order_fill_transaction(self, take_profit_order_fill_transaction):
        """Sets the take_profit_order_fill_transaction of this InlineResponse20028.


        :param take_profit_order_fill_transaction: The take_profit_order_fill_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderFillTransaction
        """

        self._take_profit_order_fill_transaction = take_profit_order_fill_transaction

    @property
    def take_profit_order_created_cancel_transaction(self):
        """Gets the take_profit_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501


        :return: The take_profit_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderCancelTransaction
        """
        return self._take_profit_order_created_cancel_transaction

    @take_profit_order_created_cancel_transaction.setter
    def take_profit_order_created_cancel_transaction(self, take_profit_order_created_cancel_transaction):
        """Sets the take_profit_order_created_cancel_transaction of this InlineResponse20028.


        :param take_profit_order_created_cancel_transaction: The take_profit_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderCancelTransaction
        """

        self._take_profit_order_created_cancel_transaction = take_profit_order_created_cancel_transaction

    @property
    def stop_loss_order_cancel_transaction(self):
        """Gets the stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501


        :return: The stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderCancelTransaction
        """
        return self._stop_loss_order_cancel_transaction

    @stop_loss_order_cancel_transaction.setter
    def stop_loss_order_cancel_transaction(self, stop_loss_order_cancel_transaction):
        """Sets the stop_loss_order_cancel_transaction of this InlineResponse20028.


        :param stop_loss_order_cancel_transaction: The stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderCancelTransaction
        """

        self._stop_loss_order_cancel_transaction = stop_loss_order_cancel_transaction

    @property
    def stop_loss_order_transaction(self):
        """Gets the stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501


        :return: The stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: StopLossOrderTransaction
        """
        return self._stop_loss_order_transaction

    @stop_loss_order_transaction.setter
    def stop_loss_order_transaction(self, stop_loss_order_transaction):
        """Sets the stop_loss_order_transaction of this InlineResponse20028.


        :param stop_loss_order_transaction: The stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501
        :type: StopLossOrderTransaction
        """

        self._stop_loss_order_transaction = stop_loss_order_transaction

    @property
    def stop_loss_order_fill_transaction(self):
        """Gets the stop_loss_order_fill_transaction of this InlineResponse20028.  # noqa: E501


        :return: The stop_loss_order_fill_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderFillTransaction
        """
        return self._stop_loss_order_fill_transaction

    @stop_loss_order_fill_transaction.setter
    def stop_loss_order_fill_transaction(self, stop_loss_order_fill_transaction):
        """Sets the stop_loss_order_fill_transaction of this InlineResponse20028.


        :param stop_loss_order_fill_transaction: The stop_loss_order_fill_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderFillTransaction
        """

        self._stop_loss_order_fill_transaction = stop_loss_order_fill_transaction

    @property
    def stop_loss_order_created_cancel_transaction(self):
        """Gets the stop_loss_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501


        :return: The stop_loss_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderCancelTransaction
        """
        return self._stop_loss_order_created_cancel_transaction

    @stop_loss_order_created_cancel_transaction.setter
    def stop_loss_order_created_cancel_transaction(self, stop_loss_order_created_cancel_transaction):
        """Sets the stop_loss_order_created_cancel_transaction of this InlineResponse20028.


        :param stop_loss_order_created_cancel_transaction: The stop_loss_order_created_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderCancelTransaction
        """

        self._stop_loss_order_created_cancel_transaction = stop_loss_order_created_cancel_transaction

    @property
    def trailing_stop_loss_order_cancel_transaction(self):
        """Gets the trailing_stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501


        :return: The trailing_stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: OrderCancelTransaction
        """
        return self._trailing_stop_loss_order_cancel_transaction

    @trailing_stop_loss_order_cancel_transaction.setter
    def trailing_stop_loss_order_cancel_transaction(self, trailing_stop_loss_order_cancel_transaction):
        """Sets the trailing_stop_loss_order_cancel_transaction of this InlineResponse20028.


        :param trailing_stop_loss_order_cancel_transaction: The trailing_stop_loss_order_cancel_transaction of this InlineResponse20028.  # noqa: E501
        :type: OrderCancelTransaction
        """

        self._trailing_stop_loss_order_cancel_transaction = trailing_stop_loss_order_cancel_transaction

    @property
    def trailing_stop_loss_order_transaction(self):
        """Gets the trailing_stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501


        :return: The trailing_stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501
        :rtype: TrailingStopLossOrderTransaction
        """
        return self._trailing_stop_loss_order_transaction

    @trailing_stop_loss_order_transaction.setter
    def trailing_stop_loss_order_transaction(self, trailing_stop_loss_order_transaction):
        """Sets the trailing_stop_loss_order_transaction of this InlineResponse20028.


        :param trailing_stop_loss_order_transaction: The trailing_stop_loss_order_transaction of this InlineResponse20028.  # noqa: E501
        :type: TrailingStopLossOrderTransaction
        """

        self._trailing_stop_loss_order_transaction = trailing_stop_loss_order_transaction

    @property
    def related_transaction_i_ds(self):
        """Gets the related_transaction_i_ds of this InlineResponse20028.  # noqa: E501

        The IDs of all Transactions that were created while satisfying the request.  # noqa: E501

        :return: The related_transaction_i_ds of this InlineResponse20028.  # noqa: E501
        :rtype: list[str]
        """
        return self._related_transaction_i_ds

    @related_transaction_i_ds.setter
    def related_transaction_i_ds(self, related_transaction_i_ds):
        """Sets the related_transaction_i_ds of this InlineResponse20028.

        The IDs of all Transactions that were created while satisfying the request.  # noqa: E501

        :param related_transaction_i_ds: The related_transaction_i_ds of this InlineResponse20028.  # noqa: E501
        :type: list[str]
        """

        self._related_transaction_i_ds = related_transaction_i_ds

    @property
    def last_transaction_id(self):
        """Gets the last_transaction_id of this InlineResponse20028.  # noqa: E501

        The ID of the most recent Transaction created for the Account  # noqa: E501

        :return: The last_transaction_id of this InlineResponse20028.  # noqa: E501
        :rtype: str
        """
        return self._last_transaction_id

    @last_transaction_id.setter
    def last_transaction_id(self, last_transaction_id):
        """Sets the last_transaction_id of this InlineResponse20028.

        The ID of the most recent Transaction created for the Account  # noqa: E501

        :param last_transaction_id: The last_transaction_id of this InlineResponse20028.  # noqa: E501
        :type: str
        """

        self._last_transaction_id = last_transaction_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20028):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
